### ISSUE TITLE
href="/static/css/common.css"  必须删掉/ 才可以

### ISSUE THREAD

**Issue by qbmiller** [carolkey/lying-admin#1]
请问你怎么测试这个? 
我直接下载后
href="/static/css/common.css"  不行
href="static/css/common.css"  必须把第一个目录/ 删掉才可以

怎么定义路由? 
1. 我用 Hbuilder 学习开发;  
http://127.0.0.1:8020/lying-admin/index.html?__hbt=1526383826602
2. 直接双击index也不行....
file:///Users/miller/workplace/lying-admin/index.html

--补充, 搞定了,apache 设置根目录问题... 用了mamp

**Comment by suyar** [comment]
嗯，之前是因为选项卡的链接是用作选项卡的唯一标识，所以必须写成绝对路径或者完整url，您可以自己修改路径
